--- 
- name: download Jenkins repo 
  get_url: 
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo 
    dest: /etc/yum.repos.d/jenkins.repo 
    validate_certs: no 
 
- name: import jenkins key 
  rpm_key: 
    state: present 
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key 
    validate_certs: no 
 
- name: install epel 
  yum: 
    name: epel-release 
    state: present 
 
- name: install jenkins 
  yum: 
    name: jenkins 
    state: latest 
 
- name: start jenkins 
  systemd: 
    name: jenkins 
    enabled: yes 
    state: started 

